# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'AddWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractButton, QApplication, QComboBox, QDateTimeEdit,
    QDialog, QDialogButtonBox, QLabel, QLineEdit,
    QListWidget, QListWidgetItem, QSizePolicy, QTabWidget,
    QTextEdit, QWidget)

class Ui_AddWindow(object):
    def setupUi(self, AddWindow):
        if not AddWindow.objectName():
            AddWindow.setObjectName(u"AddWindow")
        AddWindow.setEnabled(True)
        AddWindow.resize(643, 332)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AddWindow.sizePolicy().hasHeightForWidth())
        AddWindow.setSizePolicy(sizePolicy)
        AddWindow.setMinimumSize(QSize(643, 332))
        AddWindow.setMaximumSize(QSize(643, 332))
        AddWindow.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        AddWindow.setFocusPolicy(Qt.TabFocus)
        AddWindow.setSizeGripEnabled(False)
        self.AddTabs = QTabWidget(AddWindow)
        self.AddTabs.setObjectName(u"AddTabs")
        self.AddTabs.setGeometry(QRect(10, 10, 621, 311))
        sizePolicy.setHeightForWidth(self.AddTabs.sizePolicy().hasHeightForWidth())
        self.AddTabs.setSizePolicy(sizePolicy)
        self.AddTabs.setMinimumSize(QSize(0, 0))
        self.AddTabs.setMaximumSize(QSize(16777215, 16777215))
        self.AddTabs.setTabPosition(QTabWidget.North)
        self.AddTabs.setTabShape(QTabWidget.Rounded)
        self.taskTab = QWidget()
        self.taskTab.setObjectName(u"taskTab")
        sizePolicy.setHeightForWidth(self.taskTab.sizePolicy().hasHeightForWidth())
        self.taskTab.setSizePolicy(sizePolicy)
        self.taskTab.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.TaskTitleInput = QTextEdit(self.taskTab)
        self.TaskTitleInput.setObjectName(u"TaskTitleInput")
        self.TaskTitleInput.setGeometry(QRect(10, 10, 141, 41))
        self.TaskTitleInput.viewport().setProperty(u"cursor", QCursor(Qt.CursorShape.IBeamCursor))
        self.TaskDescInput = QTextEdit(self.taskTab)
        self.TaskDescInput.setObjectName(u"TaskDescInput")
        self.TaskDescInput.setGeometry(QRect(10, 60, 291, 221))
        self.TaskDescInput.viewport().setProperty(u"cursor", QCursor(Qt.CursorShape.IBeamCursor))
        self.TaskDateLabel = QLabel(self.taskTab)
        self.TaskDateLabel.setObjectName(u"TaskDateLabel")
        self.TaskDateLabel.setGeometry(QRect(380, 140, 61, 31))
        self.TaskRepeat = QComboBox(self.taskTab)
        self.TaskRepeat.addItem("")
        self.TaskRepeat.addItem("")
        self.TaskRepeat.addItem("")
        self.TaskRepeat.addItem("")
        self.TaskRepeat.addItem("")
        self.TaskRepeat.setObjectName(u"TaskRepeat")
        self.TaskRepeat.setGeometry(QRect(450, 180, 151, 22))
        self.TaskRepeat.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.TaskPriorityValue = QComboBox(self.taskTab)
        self.TaskPriorityValue.addItem("")
        self.TaskPriorityValue.addItem("")
        self.TaskPriorityValue.addItem("")
        self.TaskPriorityValue.setObjectName(u"TaskPriorityValue")
        self.TaskPriorityValue.setGeometry(QRect(320, 50, 111, 22))
        self.TaskPriorityValue.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.TaskDate = QDateTimeEdit(self.taskTab)
        self.TaskDate.setObjectName(u"TaskDate")
        self.TaskDate.setGeometry(QRect(450, 140, 151, 31))
        self.TaskDate.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.TaskDate.setDateTime(QDateTime(QDate(2024, 10, 1), QTime(0, 0, 0)))
        self.TaskDate.setCalendarPopup(True)
        self.TaskTagInput = QLineEdit(self.taskTab)
        self.TaskTagInput.setObjectName(u"TaskTagInput")
        self.TaskTagInput.setGeometry(QRect(450, 10, 151, 31))
        self.TaskTagInput.setClearButtonEnabled(False)
        self.TaskTags = QListWidget(self.taskTab)
        self.TaskTags.setObjectName(u"TaskTags")
        self.TaskTags.setGeometry(QRect(450, 50, 151, 71))
        self.TaskTags.viewport().setProperty(u"cursor", QCursor(Qt.CursorShape.IBeamCursor))
        self.TaskDialogButtonBox = QDialogButtonBox(self.taskTab)
        self.TaskDialogButtonBox.setObjectName(u"TaskDialogButtonBox")
        self.TaskDialogButtonBox.setGeometry(QRect(410, 240, 193, 31))
        self.TaskDialogButtonBox.setStandardButtons(QDialogButtonBox.Cancel|QDialogButtonBox.Ok)
        self.AddTabs.addTab(self.taskTab, "")
        self.eventTab = QWidget()
        self.eventTab.setObjectName(u"eventTab")
        sizePolicy.setHeightForWidth(self.eventTab.sizePolicy().hasHeightForWidth())
        self.eventTab.setSizePolicy(sizePolicy)
        self.EventDateLabel = QLabel(self.eventTab)
        self.EventDateLabel.setObjectName(u"EventDateLabel")
        self.EventDateLabel.setGeometry(QRect(350, 90, 31, 31))
        self.EventDate = QDateTimeEdit(self.eventTab)
        self.EventDate.setObjectName(u"EventDate")
        self.EventDate.setGeometry(QRect(390, 90, 151, 31))
        self.EventDate.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.EventDate.setDateTime(QDateTime(QDate(2024, 10, 1), QTime(0, 0, 0)))
        self.EventDate.setCalendarPopup(True)
        self.EventRepeatValue = QComboBox(self.eventTab)
        self.EventRepeatValue.addItem("")
        self.EventRepeatValue.addItem("")
        self.EventRepeatValue.addItem("")
        self.EventRepeatValue.addItem("")
        self.EventRepeatValue.addItem("")
        self.EventRepeatValue.setObjectName(u"EventRepeatValue")
        self.EventRepeatValue.setGeometry(QRect(390, 130, 151, 22))
        self.EventRepeatValue.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.EventTitleInput = QTextEdit(self.eventTab)
        self.EventTitleInput.setObjectName(u"EventTitleInput")
        self.EventTitleInput.setGeometry(QRect(10, 10, 141, 41))
        self.EventTitleInput.viewport().setProperty(u"cursor", QCursor(Qt.CursorShape.IBeamCursor))
        self.EventDescInput = QTextEdit(self.eventTab)
        self.EventDescInput.setObjectName(u"EventDescInput")
        self.EventDescInput.setGeometry(QRect(10, 60, 291, 221))
        self.EventDialogButtonBox = QDialogButtonBox(self.eventTab)
        self.EventDialogButtonBox.setObjectName(u"EventDialogButtonBox")
        self.EventDialogButtonBox.setGeometry(QRect(410, 240, 193, 31))
        self.EventDialogButtonBox.setStandardButtons(QDialogButtonBox.Cancel|QDialogButtonBox.Ok)
        self.AddTabs.addTab(self.eventTab, "")

        self.retranslateUi(AddWindow)

        self.AddTabs.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(AddWindow)
    # setupUi

    def retranslateUi(self, AddWindow):
        AddWindow.setWindowTitle(QCoreApplication.translate("AddWindow", u"Add Window", None))
#if QT_CONFIG(accessibility)
        self.AddTabs.setAccessibleName(QCoreApplication.translate("AddWindow", u"task", None))
#endif // QT_CONFIG(accessibility)
        self.TaskTitleInput.setPlaceholderText(QCoreApplication.translate("AddWindow", u"Title", None))
        self.TaskDescInput.setPlaceholderText(QCoreApplication.translate("AddWindow", u"Description", None))
        self.TaskDateLabel.setText(QCoreApplication.translate("AddWindow", u"Due Date", None))
        self.TaskRepeat.setItemText(0, QCoreApplication.translate("AddWindow", u"No Repeating", None))
        self.TaskRepeat.setItemText(1, QCoreApplication.translate("AddWindow", u"Daily", None))
        self.TaskRepeat.setItemText(2, QCoreApplication.translate("AddWindow", u"Weekly", None))
        self.TaskRepeat.setItemText(3, QCoreApplication.translate("AddWindow", u"Monthly", None))
        self.TaskRepeat.setItemText(4, QCoreApplication.translate("AddWindow", u"Yearly", None))

#if QT_CONFIG(tooltip)
        self.TaskRepeat.setToolTip(QCoreApplication.translate("AddWindow", u"Repeating due date", None))
#endif // QT_CONFIG(tooltip)
        self.TaskPriorityValue.setItemText(0, QCoreApplication.translate("AddWindow", u"High Priority", None))
        self.TaskPriorityValue.setItemText(1, QCoreApplication.translate("AddWindow", u"Moderate Priority", None))
        self.TaskPriorityValue.setItemText(2, QCoreApplication.translate("AddWindow", u"Low Priority", None))

#if QT_CONFIG(tooltip)
        self.TaskPriorityValue.setToolTip(QCoreApplication.translate("AddWindow", u"Priority is useful for filtering", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.TaskTagInput.setToolTip(QCoreApplication.translate("AddWindow", u"<html><head/><body><p>A tag should have no spaces. </p><p>Press enter to add tag</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.TaskTagInput.setWhatsThis(QCoreApplication.translate("AddWindow", u"<html><head/><body><p>Tags are optional feature for categorizing events/tasks</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.TaskTagInput.setInputMask("")
        self.TaskTagInput.setText("")
        self.TaskTagInput.setPlaceholderText(QCoreApplication.translate("AddWindow", u"Insert a Tag", None))
        self.AddTabs.setTabText(self.AddTabs.indexOf(self.taskTab), QCoreApplication.translate("AddWindow", u"Task", None))
        self.EventDateLabel.setText(QCoreApplication.translate("AddWindow", u"Date", None))
        self.EventRepeatValue.setItemText(0, QCoreApplication.translate("AddWindow", u"No Repeating", None))
        self.EventRepeatValue.setItemText(1, QCoreApplication.translate("AddWindow", u"Daily", None))
        self.EventRepeatValue.setItemText(2, QCoreApplication.translate("AddWindow", u"Weekly", None))
        self.EventRepeatValue.setItemText(3, QCoreApplication.translate("AddWindow", u"Monthly", None))
        self.EventRepeatValue.setItemText(4, QCoreApplication.translate("AddWindow", u"Yearly", None))

#if QT_CONFIG(tooltip)
        self.EventRepeatValue.setToolTip(QCoreApplication.translate("AddWindow", u"Repeating due date", None))
#endif // QT_CONFIG(tooltip)
        self.EventTitleInput.setPlaceholderText(QCoreApplication.translate("AddWindow", u"Title", None))
        self.EventDescInput.setPlaceholderText(QCoreApplication.translate("AddWindow", u"Description", None))
        self.AddTabs.setTabText(self.AddTabs.indexOf(self.eventTab), QCoreApplication.translate("AddWindow", u"Event", None))
    # retranslateUi

