# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'AddWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDateTimeEdit, QDialog,
    QLabel, QLineEdit, QListWidget, QListWidgetItem,
    QPushButton, QSizePolicy, QTabWidget, QTextEdit,
    QWidget)

class Ui_AddWindow(object):
    def setupUi(self, AddWindow):
        if not AddWindow.objectName():
            AddWindow.setObjectName(u"AddWindow")
        AddWindow.resize(634, 328)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AddWindow.sizePolicy().hasHeightForWidth())
        AddWindow.setSizePolicy(sizePolicy)
        AddWindow.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        AddWindow.setFocusPolicy(Qt.TabFocus)
        AddWindow.setSizeGripEnabled(False)
        self.AddTabs = QTabWidget(AddWindow)
        self.AddTabs.setObjectName(u"AddTabs")
        self.AddTabs.setGeometry(QRect(10, 10, 611, 311))
        self.AddTabs.setTabPosition(QTabWidget.North)
        self.AddTabs.setTabShape(QTabWidget.Rounded)
        self.taskTab = QWidget()
        self.taskTab.setObjectName(u"taskTab")
        self.taskTab.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.TaskTitleInput = QTextEdit(self.taskTab)
        self.TaskTitleInput.setObjectName(u"TaskTitleInput")
        self.TaskTitleInput.setGeometry(QRect(10, 10, 131, 31))
        self.TaskDescInput = QTextEdit(self.taskTab)
        self.TaskDescInput.setObjectName(u"TaskDescInput")
        self.TaskDescInput.setGeometry(QRect(10, 50, 291, 221))
        self.TaskDateLabel = QLabel(self.taskTab)
        self.TaskDateLabel.setObjectName(u"TaskDateLabel")
        self.TaskDateLabel.setGeometry(QRect(380, 140, 61, 31))
        self.TaskRepeat = QComboBox(self.taskTab)
        self.TaskRepeat.addItem("")
        self.TaskRepeat.addItem("")
        self.TaskRepeat.addItem("")
        self.TaskRepeat.addItem("")
        self.TaskRepeat.addItem("")
        self.TaskRepeat.setObjectName(u"TaskRepeat")
        self.TaskRepeat.setGeometry(QRect(470, 180, 111, 22))
        self.TaskPriorityValue = QComboBox(self.taskTab)
        self.TaskPriorityValue.addItem("")
        self.TaskPriorityValue.addItem("")
        self.TaskPriorityValue.addItem("")
        self.TaskPriorityValue.setObjectName(u"TaskPriorityValue")
        self.TaskPriorityValue.setGeometry(QRect(320, 50, 111, 22))
        self.TaskDate = QDateTimeEdit(self.taskTab)
        self.TaskDate.setObjectName(u"TaskDate")
        self.TaskDate.setGeometry(QRect(450, 140, 151, 31))
        self.TaskDate.setDateTime(QDateTime(QDate(2024, 10, 1), QTime(0, 0, 0)))
        self.TaskDate.setCalendarPopup(True)
        self.TaskTagInput = QLineEdit(self.taskTab)
        self.TaskTagInput.setObjectName(u"TaskTagInput")
        self.TaskTagInput.setGeometry(QRect(470, 10, 111, 31))
        self.TaskTagInput.setClearButtonEnabled(False)
        self.TaskCancelButton = QPushButton(self.taskTab)
        self.TaskCancelButton.setObjectName(u"TaskCancelButton")
        self.TaskCancelButton.setGeometry(QRect(520, 240, 71, 28))
        self.TaskTags = QListWidget(self.taskTab)
        self.TaskTags.setObjectName(u"TaskTags")
        self.TaskTags.setGeometry(QRect(450, 50, 151, 71))
        self.TaskAddButton = QPushButton(self.taskTab)
        self.TaskAddButton.setObjectName(u"TaskAddButton")
        self.TaskAddButton.setGeometry(QRect(440, 240, 71, 28))
        self.AddTabs.addTab(self.taskTab, "")
        self.eventTab = QWidget()
        self.eventTab.setObjectName(u"eventTab")
        self.EventTagInput = QLineEdit(self.eventTab)
        self.EventTagInput.setObjectName(u"EventTagInput")
        self.EventTagInput.setGeometry(QRect(470, 10, 111, 31))
        self.EventTagInput.setClearButtonEnabled(False)
        self.EventDateLabel = QLabel(self.eventTab)
        self.EventDateLabel.setObjectName(u"EventDateLabel")
        self.EventDateLabel.setGeometry(QRect(410, 140, 31, 31))
        self.EventDate = QDateTimeEdit(self.eventTab)
        self.EventDate.setObjectName(u"EventDate")
        self.EventDate.setGeometry(QRect(450, 140, 151, 31))
        self.EventDate.setDateTime(QDateTime(QDate(2024, 10, 1), QTime(0, 0, 0)))
        self.EventDate.setCalendarPopup(True)
        self.EventAddButton = QPushButton(self.eventTab)
        self.EventAddButton.setObjectName(u"EventAddButton")
        self.EventAddButton.setGeometry(QRect(440, 240, 71, 28))
        self.EventCancelButton = QPushButton(self.eventTab)
        self.EventCancelButton.setObjectName(u"EventCancelButton")
        self.EventCancelButton.setGeometry(QRect(520, 240, 71, 28))
        self.EventRepeatValue = QComboBox(self.eventTab)
        self.EventRepeatValue.addItem("")
        self.EventRepeatValue.addItem("")
        self.EventRepeatValue.addItem("")
        self.EventRepeatValue.addItem("")
        self.EventRepeatValue.addItem("")
        self.EventRepeatValue.setObjectName(u"EventRepeatValue")
        self.EventRepeatValue.setGeometry(QRect(470, 180, 111, 22))
        self.EventTitleInput = QTextEdit(self.eventTab)
        self.EventTitleInput.setObjectName(u"EventTitleInput")
        self.EventTitleInput.setGeometry(QRect(10, 10, 131, 31))
        self.EventDescInput = QTextEdit(self.eventTab)
        self.EventDescInput.setObjectName(u"EventDescInput")
        self.EventDescInput.setGeometry(QRect(10, 50, 291, 221))
        self.EventPriorityValue = QComboBox(self.eventTab)
        self.EventPriorityValue.addItem("")
        self.EventPriorityValue.addItem("")
        self.EventPriorityValue.addItem("")
        self.EventPriorityValue.setObjectName(u"EventPriorityValue")
        self.EventPriorityValue.setGeometry(QRect(320, 50, 111, 22))
        self.EventTags = QListWidget(self.eventTab)
        self.EventTags.setObjectName(u"EventTags")
        self.EventTags.setGeometry(QRect(450, 50, 151, 71))
        self.AddTabs.addTab(self.eventTab, "")

        self.retranslateUi(AddWindow)

        self.AddTabs.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(AddWindow)
    # setupUi

    def retranslateUi(self, AddWindow):
        AddWindow.setWindowTitle(QCoreApplication.translate("AddWindow", u"Add Window", None))
#if QT_CONFIG(accessibility)
        self.AddTabs.setAccessibleName(QCoreApplication.translate("AddWindow", u"task", None))
#endif // QT_CONFIG(accessibility)
        self.TaskTitleInput.setPlaceholderText(QCoreApplication.translate("AddWindow", u"Title", None))
        self.TaskDescInput.setPlaceholderText(QCoreApplication.translate("AddWindow", u"Description", None))
        self.TaskDateLabel.setText(QCoreApplication.translate("AddWindow", u"Due Date", None))
        self.TaskRepeat.setItemText(0, QCoreApplication.translate("AddWindow", u"No Repeating", None))
        self.TaskRepeat.setItemText(1, QCoreApplication.translate("AddWindow", u"Daily", None))
        self.TaskRepeat.setItemText(2, QCoreApplication.translate("AddWindow", u"Weekly", None))
        self.TaskRepeat.setItemText(3, QCoreApplication.translate("AddWindow", u"Monthly", None))
        self.TaskRepeat.setItemText(4, QCoreApplication.translate("AddWindow", u"Yearly", None))

#if QT_CONFIG(tooltip)
        self.TaskRepeat.setToolTip(QCoreApplication.translate("AddWindow", u"Repeating due date", None))
#endif // QT_CONFIG(tooltip)
        self.TaskPriorityValue.setItemText(0, QCoreApplication.translate("AddWindow", u"High Priority", None))
        self.TaskPriorityValue.setItemText(1, QCoreApplication.translate("AddWindow", u"Moderate Priority", None))
        self.TaskPriorityValue.setItemText(2, QCoreApplication.translate("AddWindow", u"Low Priority", None))

#if QT_CONFIG(tooltip)
        self.TaskPriorityValue.setToolTip(QCoreApplication.translate("AddWindow", u"Priority is useful for filtering", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.TaskTagInput.setToolTip(QCoreApplication.translate("AddWindow", u"<html><head/><body><p>A tag should have no spaces. </p><p>Press enter to add tag</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.TaskTagInput.setWhatsThis(QCoreApplication.translate("AddWindow", u"<html><head/><body><p>Tags are optional feature for categorizing events/tasks</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.TaskTagInput.setInputMask("")
        self.TaskTagInput.setText("")
        self.TaskTagInput.setPlaceholderText(QCoreApplication.translate("AddWindow", u"Insert a Tag", None))
        self.TaskCancelButton.setText(QCoreApplication.translate("AddWindow", u"Cancel", None))
        self.TaskAddButton.setText(QCoreApplication.translate("AddWindow", u"Add", None))
        self.AddTabs.setTabText(self.AddTabs.indexOf(self.taskTab), QCoreApplication.translate("AddWindow", u"Task", None))
#if QT_CONFIG(tooltip)
        self.EventTagInput.setToolTip(QCoreApplication.translate("AddWindow", u"<html><head/><body><p>A tag should have no spaces. </p><p>Press enter to add tag</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.EventTagInput.setWhatsThis(QCoreApplication.translate("AddWindow", u"<html><head/><body><p>Tags are optional feature for categorizing events/tasks</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.EventTagInput.setInputMask("")
        self.EventTagInput.setText("")
        self.EventTagInput.setPlaceholderText(QCoreApplication.translate("AddWindow", u"Insert a Tag", None))
        self.EventDateLabel.setText(QCoreApplication.translate("AddWindow", u"Date", None))
        self.EventAddButton.setText(QCoreApplication.translate("AddWindow", u"Add", None))
        self.EventCancelButton.setText(QCoreApplication.translate("AddWindow", u"Cancel", None))
        self.EventRepeatValue.setItemText(0, QCoreApplication.translate("AddWindow", u"No Repeating", None))
        self.EventRepeatValue.setItemText(1, QCoreApplication.translate("AddWindow", u"Daily", None))
        self.EventRepeatValue.setItemText(2, QCoreApplication.translate("AddWindow", u"Weekly", None))
        self.EventRepeatValue.setItemText(3, QCoreApplication.translate("AddWindow", u"Monthly", None))
        self.EventRepeatValue.setItemText(4, QCoreApplication.translate("AddWindow", u"Yearly", None))

#if QT_CONFIG(tooltip)
        self.EventRepeatValue.setToolTip(QCoreApplication.translate("AddWindow", u"Repeating due date", None))
#endif // QT_CONFIG(tooltip)
        self.EventTitleInput.setPlaceholderText(QCoreApplication.translate("AddWindow", u"Title", None))
        self.EventDescInput.setPlaceholderText(QCoreApplication.translate("AddWindow", u"Description", None))
        self.EventPriorityValue.setItemText(0, QCoreApplication.translate("AddWindow", u"High Priority", None))
        self.EventPriorityValue.setItemText(1, QCoreApplication.translate("AddWindow", u"Moderate Priority", None))
        self.EventPriorityValue.setItemText(2, QCoreApplication.translate("AddWindow", u"Low Priority", None))

#if QT_CONFIG(tooltip)
        self.EventPriorityValue.setToolTip(QCoreApplication.translate("AddWindow", u"Priority is useful for filtering", None))
#endif // QT_CONFIG(tooltip)
        self.AddTabs.setTabText(self.AddTabs.indexOf(self.eventTab), QCoreApplication.translate("AddWindow", u"Event", None))
    # retranslateUi

